### PR TITLE
feat!: Update request.py in order to allow Streaming responses

### PR DESCRIPTION
**Pull request by TheoBessel**
(Example : needed to build correct ChatGPT XBlocks)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @TheoBessel! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @TheoBessel! Thanks for this contribution! Please let me know if you have any questions regarding submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base).

**Comment by mphilbrick211** [comment]
> Hi @TheoBessel! Thanks for this contribution! Please let me know if you have any questions regarding submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base).

Hi @TheoBessel! Just following up on this. Please let us know when you submit your CLA form. Thanks!

**Comment by TheoBessel** [comment]
> > Hi @TheoBessel! Thanks for this contribution! Please let me know if you have any questions regarding submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base).
> 
> Hi @TheoBessel! Just following up on this. Please let us know when you submit your CLA form. Thanks!

Hi, thanks for your reply ! I have just submitted my CLA form !

**Comment by mphilbrick211** [comment]
> > > Hi @TheoBessel! Thanks for this contribution! Please let me know if you have any questions regarding submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base).
> > 
> > 
> > Hi @TheoBessel! Just following up on this. Please let us know when you submit your CLA form. Thanks!
> 
> Hi, @mphilbrick211 thanks for your reply ! I have just submitted my CLA form !

Great! The change should be reflected within 24 hours. When you re-run your checks after that, the check next to the CLA requirement should turn green.

**Comment by TheoBessel** [comment]
@mphilbrick211 Do I have to do anything else now ?

**Comment by mphilbrick211** [comment]
Hi @TheoBessel - I will look into getting the checks re-enabled for you!

**Comment by TheoBessel** [comment]
> Hi @TheoBessel - I will look into getting the checks re-enabled for you!

@mphilbrick211 Thanks a lot for your help !

**Comment by TheoBessel** [comment]
@mphilbrick211 Hello ! Any news ?

**Comment by mphilbrick211** [comment]
> @mphilbrick211 Hello ! Any news ?

Hi @TheoBessel - thanks for checking in, and for your patience. The checks should be enabled today. Apologies for the delay.

**Comment by TheoBessel** [comment]
@mphilbrick211 @nedbat Hello ! I've edited my code because it didn't pass the tests. Should I also to edit my commit messages or they are okay ? Let me know. I'll also make a PR on `edx-platform` and `xblock-sdk` in order to make the change I've proposed usable on these sides.
Have a nice day !

**Comment by TheoBessel** [comment]
@mphilbrick211 Hello ! Have you seen my last comment ?

**Comment by TheoBessel** [comment]
@e0d Updated the too long commit message and added some unit tests, it should pass all workflows now (I hope)

**Comment by TheoBessel** [comment]
@e0d I hope this time it will be good (I removed a test I wrote and that made no sense for Streaming Responses and that was failing because of that)

**Comment by TheoBessel** [comment]
@e0d ?

**Comment by TheoBessel** [comment]
Can somebody here merge my pull request ? It passes all the checks now.

**Review by ormsbee — APPROVED** [review]

**Comment by ormsbee** [comment]
@TheoBessel: Please resolve conflicts and squash your commits and I'll merge.

**Comment by TheoBessel** [comment]
> @TheoBessel: Please resolve conflicts and squash your commits and I'll merge.

I'm sorry, but I don't really know what you're talking about. I don't see any conflicts ans my commits were already amended in order to have correct messages. 🤔

**Comment by ormsbee** [comment]
Ah, sorry, I saw this:

Screenshot 2024-05-15 at 12 24 53 PM

And it didn't click to me that you did a merge instead of a rebase off of master (it's fine, it's just not what I'm used to). I'll squash and merge now.

**Comment by openedx-webhooks** [comment]
@TheoBessel 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/XBlock&entry.867055334=https://github.com/openedx/XBlock/pull/737&entry.1484655318=https://github.com/TheoBessel&entry.752974735=2024-04-11+23:20&entry.1917517419=2024-05-15+16:29&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by ormsbee** [comment]
Note for anyone looking at this later: I wasn't paying attention to the top line of the squashed commit message, and merged it in with the `feat!:` it got from the original title of this PR, rather than `feat:`, which is what it should be.

I'll make a new PR to bump the version of this package and tag it for PyPI.

**Pull request merged**
