### PR TITLE
A little bit course import logic modification

### PR DESCRIPTION
**Pull request by 110035**
First of all, thank openedx , it is an awesome project.
We are using  openedx platform for our online E-learning,  we have a problem when migrate courses from partner's platform because of few xblock missing, to avoid build the whole courses manually,  I  create this modification. this saves our a large amount time.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @110035!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @110035 - Thanks for your submission! Just checking in to see if you plan to pursue this PR? If so, you will need to complete a CLA form as mentioned above.

**Comment by mphilbrick211** [comment]
Hi @110035! Just following up on this to see if you plan to pursue. Please let me know. Thanks!

**Comment by mphilbrick211** [comment]
Closing due to inactivity. Can be reopened at a later date if appropriate.

**Comment by openedx-webhooks** [comment]
@110035 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/XBlock&entry.867055334=https://github.com/openedx/XBlock/pull/614&entry.1484655318=https://github.com/110035&entry.752974735=2022-10-20+03:19&entry.1917517419=2023-01-23+20:54&entry.2133058324=No) so we can improve your experience in the future.

**Comment by 110035** [comment]
> Hi @110035! Just following up on this to see if you plan to pursue. Please let me know. Thanks!

Hi @mphilbrick211,  I want submit this PR , but i don't get a CLA response（btw, i have submit CLA form already）,thanks

**Comment by 110035** [comment]
I am sorry , i was stucked because of China Spring Festival , so , how can i reopen this pr? thanks @mphilbrick211

**Comment by mphilbrick211** [comment]
Hi @110035! I have reopened this for you. You'll need to re-run the failing tests and address the branch date error. Please let me know if you have any questions.

**Comment by mphilbrick211** [comment]
Hi @110035! Just following up on my comment above re: your CLA form :)

**Comment by mphilbrick211** [comment]
> > Hi @110035! Just following up on this to see if you plan to pursue. Please let me know. Thanks!
> 
> Hi @mphilbrick211, I want submit this PR , but i don't get a CLA response（btw, i have submit CLA form already）,thanks

@110035 I apologize that your CLA check is still failing - we had some issues on our end re: the CLA processing and yours may not have gone through. If you re-run your tests, your CLA check would turn green if it was received. If not, you will need to submit again. Sorry for the inconvenience.

**Comment by 110035** [comment]
> > > Hi @110035! Just following up on this to see if you plan to pursue. Please let me know. Thanks!
> > 
> > 
> > Hi @mphilbrick211, I want submit this PR , but i don't get a CLA response（btw, i have submit CLA form already）,thanks
> 
> @110035 I apologize that your CLA check is still failing - we had some issues on our end re: the CLA processing and yours may not have gone through. If you re-run your tests, your CLA check would turn green if it was received. If not, you will need to submit again. Sorry for the inconvenience.

@mphilbrick211  Thanks for your reply. I updated PR status, It seems that only the CLA status is wrong . Please take a look.

**Comment by mphilbrick211** [comment]
@110035 I will look into this for you.

**Comment by 110035** [comment]
> @110035 I will look into this for you.

thank you so much

**Comment by mphilbrick211** [comment]
Hi @e0d - would you mind taking a look at this? I don't see that the CLA has gone through, but perhaps he can try again after the tests are enabled?

**Comment by 110035** [comment]
> @110035 I don't think we could accept this change as is, I don't think everyone would want to automatically fall back to the htmlxblock as it might indicated some issue with their deployment. I could imagine this being an optional capabilty though. What do you think about having this be an optional behaviour based on a new parameter? the default would be to through the exception but if a `fallback_xblock` is provided, that could be used instead.

@feanil Yes i totally agree with you , a new parameter is a good solution , for example ,if there is a setting.course_import_greedy : true , then the logic goes to greedy model ,ie, ignore the missing xblock plugin and import as much content as possible.

**Comment by e0d** [comment]
This branch was out of date with master.  I've added a merge commit to pull in the changes.  Tests are running.  @mphilbrick211

**Comment by e0d** [comment]
@110035 There are some failing tests and linting issues that need to be addressed.

**Comment by mphilbrick211** [comment]
Hi @110035 - just checking in to see if you plan on pursuing this pull request?

**Comment by 110035** [comment]
> Hi @110035 - just checking in to see if you plan on pursuing this pull request?

Hi @mphilbrick211 absolutly yes .    I will do a few changes based on @feanil 's suggestions.

**Comment by mphilbrick211** [comment]
> > Hi @110035 - just checking in to see if you plan on pursuing this pull request?
> 
> Hi @mphilbrick211 absolutly yes . I will do a few changes based on @feanil 's suggestions.

Great, @110035! We still need your CLA submitted before we can push any changes through.

**Comment by mphilbrick211** [comment]
Hi @110035! Friendly ping on this :)

**Comment by mphilbrick211** [comment]
> Hi @110035! Friendly ping on this :)

Hi @110035! Friendly reminder on the CLA form - were you able to submit? If you submitted it, the CLA check should turn green when you re-run the tests. Please let me know if you have any questions. Thanks!

**Comment by mphilbrick211** [comment]
Hi @110035! I'm going to close this PR for now. We can reopen if you choose to pursue in the future. Thanks!

**Comment by openedx-webhooks** [comment]
@110035 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/XBlock&entry.867055334=https://github.com/openedx/XBlock/pull/614&entry.1484655318=https://github.com/110035&entry.752974735=2022-10-20+03:19&entry.1917517419=2023-04-21+18:05&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
